#!/bin/bash

friends=( "Marcus The Rich" "JJ The Short" "Timid Thomas" "Michelangelo The Mobster" )


	# My first friend (in the list).
	
	# My friends whose names start with M.

	# My short friends.

	# Friends I kind of didn't bother to remember.
